### ISSUE TITLE
Migrate to QT5

### ISSUE THREAD

**Issue by helioloureiro** [helioloureiro/raspresenterpy#1]
Since QT5 is already release and even the main raspberrypi distro moved toward the recent Debian stretch release, which is qt5 based, it is time to update it.

**Comment by dankolbrs** [comment]
Hey @helioloureiro! Thanks for using the `hacktoberfest` label!

I've got PR #2 for the PyQt5 changes. Let me know in there if you've got other changes you'd like to see.

Also, how do you feel about some general flake updates? I'd be happy to do another PR on this to take care of some of PEP formatting issues.

**Comment by helioloureiro** [comment]
Greate work!

I will create more two issues so you can close them and count for #hacktoberfest (actually commits are enough, but well... get more visibility).

**Comment by helioloureiro** [comment]
> Hey @helioloureiro! Thanks for using the `hacktoberfest` label!
> 
> I've got PR #2 for the PyQt5 changes. Let me know in there if you've got other changes you'd like to see.
> 
> Also, how do you feel about some general flake updates? I'd be happy to do another PR on this to take care of some of PEP formatting issues.

It is there: https://github.com/helioloureiro/raspresenterpy/issues/3
